apiVersion: v1
kind: Service
metadata:
  name: {{ include "squeeze.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "squeeze.name" . }}
    helm.sh/chart: {{ include "squeeze.chart" . }}
spec:
  ports:
  - port: 9998
    name: "http"
    targetPort: 9998
  - port: 9997
    targetPort: 9997
    name: "grpc"
  selector:
    app: squeeze
    role: master
    tier: backend
