
apiVersion: v1
kind: Namespace
metadata:
  name: squeeze

---
# Source: squeeze/templates/service-master.yaml
apiVersion: v1
kind: Service
metadata:
  name: squeeze-master
  namespace: squeeze
  labels:
    app.kubernetes.io/name: squeeze
    helm.sh/chart: squeeze-0.1
spec:
  ports:
    - port: 9998
      targetPort: 9998
      name: "http"
    - port: 9997
      targetPort: 9997
      name: "grpc"
  selector:
    app: squeeze-master
---
# Source: squeeze/templates/service-slave.yaml
apiVersion: v1
kind: Service
metadata:
  name: squeeze-slave
  namespace: squeeze
  labels:
    app.kubernetes.io/name: squeeze
    helm.sh/chart: squeeze-0.1
spec:
  ports:
    - port: 9996
      targetPort: 9996
      name: "http"
    - port: 9995
      targetPort: 9995
      name: "grpc"
  selector:
    app: squeeze-slave
---
# Source: squeeze/templates/service-web.yaml
apiVersion: v1
kind: Service
metadata:
  name: squeeze-web
  namespace: squeeze
  labels:
    app.kubernetes.io/name: squeeze
    helm.sh/chart: squeeze-0.1
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 9991
  selector:
    app: squeeze-web
---
# Source: squeeze/templates/deployment-master.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: squeeze-master
  namespace: squeeze
  labels:
    app: squeeze-master
spec:
  replicas: 1
  selector:
    matchLabels:
      app: squeeze-master
  template:
    metadata:
      labels:
        app: squeeze-master
    spec:
      containers:
        - name: squeeze-master
          image: "registry.hub.docker.com/agile6v/squeeze:v0.1.1"
          imagePullPolicy: IfNotPresent
          command:
            - squeeze
            - master
            - --alsologtostderr
            - -v=2
          ports:
            - containerPort: 9997
              name: http
            - containerPort: 9998
              name: grpc
---
# Source: squeeze/templates/deployment-slave.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: squeeze-slave
  namespace: squeeze
  labels:
    app: squeeze-slave
spec:
  replicas: 2
  selector:
    matchLabels:
      app: squeeze-slave
  template:
    metadata:
      labels:
        app: squeeze-slave
    spec:
      containers:
        - name: squeeze-slave
          image: "registry.hub.docker.com/agile6v/squeeze:v0.1.1"
          imagePullPolicy: IfNotPresent
          command:
            - squeeze
            - slave
            - --grpcMasterAddr=squeeze-master:9997
            - --httpMasterAddr=squeeze-master:9998
            - --alsologtostderr
            - -v=2
          ports:
            - containerPort: 9996
              name: http
            - containerPort: 9996
              name: grpc
---
# Source: squeeze/templates/deployment-web.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: squeeze-web
  namespace: squeeze
  labels:
    app: squeeze-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: squeeze-web
  template:
    metadata:
      labels:
        app: squeeze-web
    spec:
      containers:
        - name: squeeze-web
          image: "registry.hub.docker.com/agile6v/squeeze:v0.1.1"
          imagePullPolicy: IfNotPresent
          command:
            - squeeze
            - web
            - --dbtype=sqlite
            - --masterAddr=squeeze-master:9998
            - --alsologtostderr
          ports:
            - containerPort:  9991
              name: http