{{- if .Values.ingress.enabled -}}
{{- $fullName := include "squeeze.fullname" . -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: squeeze-ingress
  labels:
    app.kubernetes.io/name: {{ include "squeeze.name" . }}
    helm.sh/chart: {{ include "squeeze.chart" . }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  rules:
  {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          - path: /
            backend:
              serviceName: squeeze-master
              servicePort: 9998
          - path: /api/*
            backend:
              serviceName: squeeze-web
              servicePort: 9991
  {{- end }}
{{- end }}
