{{- if .Values.web.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.web.service.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ include "squeeze.name" . }}
    helm.sh/chart: {{ include "squeeze.chart" . }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.web.service.ports.http }}
  selector:
    {{- with .Values.web.deployment.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end }}